version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shcommerce
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data